import type { Metadata } from "next";
import "../globals.css";
import { Button } from "@/components/ui/button";
import { cookies } from 'next/headers'
import Navbar from "@/components/web/navbar";

const cookieStore = await cookies();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" title="YourBlog">
      <body >
        {children}
      </body>
    </html>
  );
}
