import type { Metadata } from "next";
import "../globals.css";
import { Button } from "@/components/ui/button";
import { cookies } from 'next/headers'
import Navbar from "@/components/web/navbar";

const cookieStore = await cookies();

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div >
        <h1 className=" p-4 m-4 flex flex-row justify-center text-5xl">
          YourBlogs
        </h1>
        <Navbar></Navbar>
        {children}
      </div>
  );
}
