import type { Metadata } from "next";
import "../globals.css";
import { Button } from "@/components/ui/button";
import { cookies } from 'next/headers'

const cookieStore = await cookies();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" title="YourBlog">
      <body >
        <h1 className=" p-4 m-4 flex flex-row justify-center text-5xl">
          YourBlogs
        </h1>
        {children}
      </body>
    </html>
  );
}
